name: Build and Publish Blazor WASM

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-blazor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Blazor WASM
      run: dotnet publish Portfolio.WASM.csproj -c Release -o build

    - name: Commit and Push published output
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add build
        git commit -m "📦 Auto-publish Blazor WASM output" || echo "No changes to commit"
        git push
